<?php
// if user clicked not deny
$cookiesAllowed = isset($_COOKIE['cookieconsent_status']) && in_array($_COOKIE['cookieconsent_status'], array('allow', 'dismiss')) ? TRUE : FALSE;
$baseUrl = ($_SERVER['SERVER_PORT'] == '80' ? 'http' : 'https') . '://' . $_SERVER['SERVER_NAME'] . str_replace('index.php', '', $_SERVER['PHP_SELF']);

if (isset($_ENV['docker']) && $_ENV['docker']) {
    $baseUrl = 'http://localhost:8080/';
}

// default setting (home page)        
$meta = array(
    'lang' => 'en',
    'title' => 'Vue Skeleton',
    'baseUrl' => $baseUrl,
    'currentUrl' => ($_SERVER['SERVER_PORT'] == '80' ? 'http' : 'https') . '://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'],
    'keywords' => '',
    'description' => '',
    'robots' => 'index,follow',
    'author' => 'InsanityMeetsHH',
    'fbAppId' => '',
    'fbAdmins' => '',
    'publisher' => '',
    'type' => 'website',
    'socialMediaImage' => '',
    'siteName' => 'Vue Skeleton',
    'twitterSite' => 'InsanityMeetsHH',
    'twitterUrl' => 'https://twitter.com/InsanityMeetsHH',
    'rssUrl' => '',
    'locale' => 'en_US',
    'themeColor' => '#212121',
);
?>

<!DOCTYPE html>
<html lang="<?php echo $meta['lang']; ?>" class="no-js">
    <head>
        <script>
            function setCookie(e,t,n){var o=new Date;o.setTime(o.getTime()+24*n*60*60*1e3);var i="expires="+o.toUTCString();document.cookie=e+"="+t+";"+i+";path=/"}function getCookie(e){for(var t=e+"=",n=decodeURIComponent(document.cookie).split(";"),o=0;o<n.length;o++){for(var i=n[o];" "==i.charAt(0);)i=i.substring(1);if(0==i.indexOf(t))return i.substring(t.length,i.length)}return""}
            var cookiesAllowed = getCookie('cookieconsent_status') !== 'deny';
            var cookieLayer = {};
            var require = {
                baseUrl: '/',
                paths: {
                    'vue': 'js/vue.js?v=2.6.10',
                    'vue-router': 'js/vue-router.js?v=3.0.6',
                    'vue-i18n': 'js/vue-i18n.js?v=8.11.2',
                    '@fortawesome/fontawesome-svg-core': 'js/fontawesome-svg-core.js?v=1.2.19',
                    '@fortawesome/free-brands-svg-icons': 'js/free-brands-svg-icons.js?v=5.9.0',
                    '@fortawesome/free-regular-svg-icons': 'js/free-regular-svg-icons.js?v=5.9.0',
                    '@fortawesome/free-solid-svg-icons': 'js/free-solid-svg-icons.js?v=5.9.0',
                    '@fortawesome/vue-fontawesome': 'js/vue-fontawesome.js?v=0.1.6'
                }
            };
        
            loadCss = function(config) {
                var head = document.getElementsByTagName('head')[0];

                if (config.content) {
                    var style  = document.createElement('style');
                    style.type = 'text/css';

                    if (style.styleSheet) {
                        style.styleSheet.cssText = config.content;
                    } else {
                        style.innerHTML = config.content;
                    }

                    head.appendChild(style);
                } else if (config.url) {
                    var link  = document.createElement('link');
                    link.href = config.url;
                    link.rel  = 'stylesheet';
                    link.type = 'text/css';
                    head.appendChild(link);
                }
            };
            
            // if cookies allowed - load tracking code
            if (cookiesAllowed) {
                // Google Analaytics, Google Tag Manager, ...
//                var s = document.createElement('script');
//                s.type = 'text/javascript';
//                s.async = true;
//                s.src = 'https://www.googletagmanager.com/gtag/js?id=UA-NUMBER-X';
//                var h = document.getElementsByTagName('head')[0];
//                h.appendChild(s, h);
//            
//                window.dataLayer = window.dataLayer || [];
//                function gtag(){dataLayer.push(arguments);}
//                gtag('js', new Date());
//                gtag('config', 'UA-NUMBER-X', {'anonymize_ip': true});
            }
        </script>
        
        <title><?php echo $meta['title']; ?></title>
        <base href="<?php echo $meta['baseUrl']; ?>">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <meta name="keywords" content="<?php echo $meta['keywords']; ?>"/>
        <meta name="description" content="<?php echo $meta['description']; ?>">
        <meta name='robots' content="<?php echo $meta['robots']; ?>">
        <meta name="author" content="<?php echo $meta['author']; ?>">
        <meta property="fb:admins" content="<?php echo $meta['fbAdmins']; ?>"/>
        <meta property="fb:app_id" content="<?php echo $meta['fbAppId']; ?>"/>
        <meta property="og:type" content="<?php echo $meta['type']; ?>"/>
        <meta property="og:title" content="<?php echo $meta['title']; ?>"/>
        <meta property="og:description" content="<?php echo $meta['description']; ?>"/>
        <meta property="og:image" content="<?php echo $meta['socialMediaImage']; ?>"/>
        <meta property="og:site_name" content="<?php echo $meta['siteName']; ?>"/>
        <meta property="og:url" content="<?php echo $meta['currentUrl']; ?>"/>
        <meta property="og:locale" content="<?php echo $meta['locale']; ?>"/>
        <meta property="article:publisher" content="<?php echo $meta['publisher']; ?>"/>
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:site" content="<?php echo $meta['twitterSite']; ?>">
        <meta name="twitter:title" content="<?php echo $meta['title']; ?>">
        <meta name="twitter:description" content="<?php echo $meta['description']; ?>">
        <meta name="twitter:image" content="<?php echo $meta['socialMediaImage']; ?>">
        <link rel="me" href="<?php echo $meta['twitterUrl']; ?>">
        <link rel="canonical" href="<?php echo $meta['currentUrl']; ?>"/>
        <link rel="alternate" hreflang="x-default" href="<?php echo $meta['currentUrl']; ?>"/>
        <!--<link rel="alternate" type="application/rss+xml" title="" href="<?php echo $meta['rssUrl']; ?>"/>-->
        <?php /** Favicon sizes 16, 32, 36, 48, 70, 72, 96, 144, 150, 180, 192, 256, 310, 310x150, 384, 512, SVG, ICO */ ?>
        <link rel="apple-touch-icon" href="img/favicons/favicon-180x180.png" sizes="180x180">
        <link rel="icon" type="image/png" href="img/favicons/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="img/favicons/favicon-192x192.png" sizes="192x192">
        <link rel="icon" type="image/png" href="img/favicons/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="img/favicons/manifest.json">
        <link rel="mask-icon" href="img/favicons/favicon.svg" color="<?php echo $meta['themeColor']; ?>">
        <meta name="msapplication-TileColor" content="<?php echo $meta['themeColor']; ?>">
        <meta name="msapplication-TileImage" content="img/favicons/favicon-144x144.png">
        <meta name="msapplication-config" content="img/favicons/browserconfig.xml">
        <meta name="theme-color" content="<?php echo $meta['themeColor']; ?>">
        <link rel="shortcut icon" href="img/favicons/favicon.ico">
        
        <link rel="stylesheet" href="css/styles.css?v=1.0.0">
    </head>
    <body>
        <div id="app"></div>
        <script src="js/scripts.js?v=1.0.0"></script>
        <script data-main="js/vue/app" src="js/require.js?v=2.3.6"></script>
    </body>
</html>
